function Regulation () {
    return (
        <div className="bg-teal-800">
            <div className="py-[6em] px-3 flex flex-col lg:max-w-screen-lg mx-auto">
                <h1 className="font-bold uppercase text-teal-300 text-xl lg:text-3xl">Datenschutzrichtlinien</h1>
                <p>Wir sind uns darüber bewusst, dass Ihnen der Schutz Ihrer Privatsphäre bei der Benutzung unseres Services ein wichtiges Anliegen ist. Wir nehmen den Schutz Ihrer persönlichen Daten sehr ernst. Deshalb möchten wir, dass Sie wissen, wann wir welche Daten speichern und wie wir sie verwenden. Sie erhalten als Nutzer unserer Internetseite in dieser Datenschutzerklärung alle notwendigen Informationen darüber, wie, in welchem Umfang sowie zu welchem Zweck wir oder Drittanbieter Daten von Ihnen erheben und diese verwenden. Die Erhebung und Nutzung Ihrer Daten erfolgt streng nach den Vorgaben des Bundesdatenschutzgesetzes (BDSG), der Datenschutzgrundverordnung (DSGVO) und des Telemediengesetzes (TMG). Wir fühlen uns der Vertraulichkeit Ihrer personenbezogenen Daten besonders verpflichtet und arbeiten deshalb streng innerhalb der Grenzen, die die gesetzlichen Vorgaben uns setzen. Die Erhebung dieser personenbezogenen Daten erfolgt auf freiwilliger Basis, wenn uns das möglich ist. Auch geben wir diese Daten nur mit Ihrer ausdrücklichen Zustimmung an Dritte weiter. Wir sorgen bei besonders vertraulichen Daten wie im Zahlungsverkehr oder im Hinblick auf Ihre Anfragen an uns durch Einsatz einer SSL-Verschlüsselung für hohe Sicherheit. Bei Problemen, Fragen oder Anregungen wenden Sie sich bitte an uns.
                </p>
                <h2 className="text-gray-900 text-2xl tracking-wider">Personenbezogene Daten</h2>
                <p>Personenbezogene Daten erheben wir im Rahmen von Datenvermeidung und Datensparsamkeit nur in dem Ausmaß und so lange, wie es zur Nutzung unserer Webseite notwendig ist, beziehungsweise vom Gesetzgeber vorgeschrieben wird. Diese Daten werden nur dann verarbeitet, wenn Sie uns diese von sich aus z. B. im Rahmen einer Registrierung, durch das Ausfüllen von Formularen oder das Versenden von E-Mails, Anfragen oder Anforderung von Material zur Verfügung stellen. Die Datenbank und ihre Inhalte bleiben in unserem Unternehmen. Ihre persönlichen Daten werden bei Aufträgen und Vertragsabschlüssen dem jeweiligen PC des Bearbeiters übermittelt. Die übermittelten Daten dienen der Absicherung Ihrer Bestellung, sowie der Kontaktaufnahme im Falle von Verschiebungen, Ihre Daten werden von uns keinen externen Dritten zur Verfügung gestellt. Wir nehmen den Schutz Ihrer persönlichen Daten ernst und halten uns bei Erhebung und Verarbeitung personenbezogener Daten streng an die entsprechenden gesetzlichen Vorschriften und an diese Datenschutzerklärung. Fällt der Zweck der Datenerhebung weg oder ist das Ende der gesetzlichen Speicherfrist erreicht, werden die erhobenen Datengesperrt oder gelöscht. Regelmäßig kann unsere Webseite ohne die Weitergabe persönlicher Daten genutzt werden. Wenn wir personenbezogene Daten erheben – etwa Ihren Namen, Ihre Anschrift oder Ihre E-Mail-Adresse – erfolgt diese Datenerhebung freiwillig. Ohne eine ausdrücklich erteilte Zustimmung von Ihrer Seite werden diese Daten Dritten nicht zur Kenntnis gebracht. Beachten Sie bitte, dass Daten im Internet allgemein nicht immer sicher übertragen werden. Besonders im E-Mail-Verkehr kann der Schutz beim Datenaustausch nicht garantiert werden.
                </p>
                <h2 className="text-gray-900 text-2xl tracking-wider">Allgemeine Datenerhebung</h2>
                <p>Beim Aufruf unserer Internetseite werden durch den auf Ihrem Endgerät genutzten Browser Informationen an den Server unserer Website gesendet. Diese Informationen werden lediglich temporär in einem sog. Logfile gespeichert. Folgende Informationen werden dabei ohne ihr Zutun erfasst und bis zur automatisierten Löschung gespeichert:
                <ul className="list-disc ml-20 my-5">
                    <li>IP-Adresse des anfragenden Rechners</li>
                    <li>Datum und Uhrzeit des Zugriffs</li>
                    <li>Name sowie URL der abgerufenen Datei</li>
                    <li>Referrer – URL = Website, von der aus der Zugriff erfolgt</li>
                    <li>Verwendeter Browser und ggf. Betriebssystem Ihres Rechners</li>
                    <li>Name Ihres Access – Providers</li>
                </ul>
                Die Zwecke der vorgenannten allgemeinen Datenerhebung sind:
                <ul className="list-disc ml-20 my-5">
                    <li>Gewährleistung eines reibungslosen Verbindungsaufbaus der Webseite</li>
                    <li>Gewährleistung einer komfortablen Nutzung unserer Webseite</li>
                    <li>Auswertung der Systemsicherheit und -stabilität</li>
                    <li>Weitere administrative Zwecke</li>
                </ul>
                Die Datenerhebung erfolgt aufgrund eines unsererseits bestehenden berechtigten Interesses gem. Art. 6 Abs. 1 S. 1 lit. f) DSGVO. Unser berechtigtes Interesse folgt aus den vorgenannten Zwecken zur Datenerhebung. Wir weisen ausdrücklich darauf hin, dass wir keine Daten zu dem Zweck verwenden, um Rückschlüsse auf Ihre Person zu ziehen.</p>
                <h2 className="text-gray-900 text-2xl tracking-wider">Auskunft, Löschung, Sperrung</h2>
                <p>Sie erhalten jederzeit unentgeltlich Auskunft über die von uns gespeicherten personenbezogenen Daten zu Ihrer Person sowie zur Herkunft, dem Empfänger und dem Zweck von Datenerhebung sowie Datenverarbeitung. Außerdem haben Sie das Recht, die Berichtigung, die Sperrung oder Löschung Ihrer Daten zu verlangen. Ausgenommen davon sind Daten, die aufgrund gesetzlicher Vorschriften aufbewahrt oder zur ordnungsgemäßen Geschäftsabwicklung benötigt werden. Damit eine Datensperre jederzeit realisiert werden kann, werden Daten zu Kontrollzwecken in einer Sperrdatei vorgehalten. Werden Daten nicht von einer gesetzlichen Archivierungspflicht erfasst, löschen wir Ihre Daten auf Ihren Wunsch. Greift die Archivierungspflicht, sperren wir Ihre Daten. Für alle Fragen und Anliegen zur Berichtigung, Sperrung oder Löschung von personenbezogenen Daten wenden Sie sich bitte an uns unter den Kontaktdaten in dieser Datenschutzerklärung bzw. an die im Impressum genannte Adresse.
                </p>
                <h2 className="text-gray-900 text-2xl tracking-wider">SSL-Verschlüsselung</h2>
                <p>Unsere Webseite bedient sich einer SSL-Verschlüsselung, wenn es um die Übermittlung vertraulicher oder persönlicher Inhalte unserer Nutzer geht. Diese Verschlüsslung wird zum Beispiel bei der Abwicklung des Zahlungsverkehrs sowie bei Anfragen aktiviert, die Sie an uns über unsere Webseite stellen. Achten Sie bitte darauf, dass die SSL-Verschlüsselung bei entsprechenden Aktivitäten von Ihrer Seite her aktiviert ist. Der Einsatz der
                Verschlüsselung ist leicht zu erkennen: Die Anzeige in Ihrer Browserzeile wechselt von „http://“ zu „https://“. Über SSL verschlüsselte Daten sind nicht von Dritten lesbar. Übermitteln Sie Ihre vertraulichen Informationen nur bei aktivierter SSL-Verschlüsselung und wenden Sie sich im Zweifel an uns.
                </p>
                <h2 className="text-gray-900 text-2xl tracking-wider">Inhalte und Dienste von Drittanbietern</h2>
                <p>Das Angebot auf unserer Webseite erfasst unter Umständen auch Inhalte, Dienste und Leistungen von anderen Anbietern, die unser Angebot ergänzen. Beispiele für solche Angebote sind Karten von Google-Maps, YouTube-Videos oder Grafikdarstellungen Dritter. Der Aufruf dieser Leistungen von dritter Seite erfordert regelmäßig die Übermittlung Ihrer IP-Adresse. Damit ist es diesen Anbietern möglich, Ihre Nutzer-IP-Adresse wahrzunehmen und diese auch zu speichern. Wir bemühen uns sehr, nur solche Drittanbieter einzubeziehen, die IP-Adressen allein zur Auslieferung der Inhalte nutzen. Wir haben dabei jedoch keinen Einfluss darauf, welcher Drittanbieter gegebenenfalls die IP-Adresse speichert. Diese Speicherung kann zum Beispiel statistischen Zwecken dienen. Sollten wir von Speicherungsvorgängen durch Drittanbieter Kenntnis erlangen, weisen wir unsere Nutzer unverzüglich auf diese Tatsache hin. Beachten Sie bitte in diesem Zusammenhang auch die speziellen Datenschutzerklärungen zu einzelnen Drittanbietern und Dienstleistern, deren Service wir auf unserer Webseite nutzen. Sie finden Sie ebenfalls in dieser Datenschutzerklärung.
                </p>
                <h2 className="text-gray-900 text-2xl tracking-wider">Erhebung von Zugriffsdaten</h2>
                <p>Die Auslieferung und Darstellung der Inhalte über unsere Webseite erfordert technisch die Erfassung bestimmter Daten. Mit Ihrem Zugriff auf unsere Webseite werden diese sogenannten Server-Logfiles durch uns oder den Provider des Webspace erfasst. Diese Logfiles erlauben keinen Rückschluss auf Sie und Ihre Person. Die entsprechenden Informationen bestehen aus dem Namen der Webseite, der Datei, dem aktuellen Datum, der Datenmenge, dem Webrowser und seiner Version, dem eingesetzten Betriebssystem, dem Domain-Namen Ihres Internet-Providers, der Referrer-URL als jene Seite, von der Sie auf unsere Seite gewechselt sind, sowie der entsprechenden IP-Adresse. Wir nutzen diese Daten zur Darstellung und Auslieferung unserer Inhalte sowie zu statistischen Zwecken. Die Informationen unterstützen die Bereitstellung und ständige Verbesserung unseres Angebots. Auch behalten wir uns vor, die erwähnten Daten nachträglich zu prüfen, sollte der Verdacht auf eine rechtswidrige Nutzung unseres Angebotes bestehen.
                </p>
                <h2 className="text-gray-900 text-2xl tracking-wider">Server Logfiles</h2>
                <p>Bei den Server Logfiles handelt es sich um anonymisierte Daten, die bei Ihrem Zugriff auf unsere Webseite erfasst werden. Diese Informationen ermöglichen keine Rückschlüsse auf Sie persönlich, sind aber aus technischen Gründen für die Auslieferung und Darstellung unserer Inhalte unverzichtbar. Weiterhin dienen Sie unserer Statistik und der ständigen Optimierung unserer Inhalte. Typische Logfiles sind das Datum und die Zeit des Zugriffs, die Datenmenge, der für den Zugriff benutzte Browser und seine Version, das eingesetzte Betriebssystem, der Domainname des von Ihnen beauftragten Providers, die Seite, von der Sie zu unserem Angebot gekommen sind (Referrer-URL) und Ihre IP-Adresse. Logfiles ermöglichen außerdem eine genaue Prüfung bei Verdacht auf eine rechtswidrige Nutzung unserer Webseite.
                </p>
                <h2 className="text-gray-900 text-2xl tracking-wider">Sicherheit Ihrer Daten</h2>
                <p>Wir setzen technische und organisatorische Sicherheitsmaßnahmen ein, um Ihre zur Verfügung gestellten Daten durch zufällige oder vorsätzliche Manipulation, Verlust, Zerstörung oder Zugriff unberechtigter Personen zu schützen. Im Falle der Erhebung und Verarbeitung persönlicher Daten werden die Informationen in verschlüsselter Form übertragen, um einem Missbrauch der Daten durch Dritte vorzubeugen. Unsere Sicherungsmaßnahmen werden entsprechend der technologischen Entwicklung fortlaufend überarbeitet. Vorbehalt der Änderung dieser Datenschutzerklärung Sowohl die Technik als natürlich auch die Auslegung von Recht und Gesetz unterliegen zuweilen einem zeitlichen Wandel. Aufgrund dessen behalten wir uns die Änderung dieser Datenschutzerklärung ausdrücklich vor.
                </p>
            </div>
        </div>
    )
}

export default Regulation;